on:
  schedule:
    - cron: 0 5 * * *
  push:
    branches:
      - main

jobs:
  build:
    container: "python:3.11.4"
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Autobuild
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          mkdir -p ~/.cache/pip
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate data
        run: |
          python3.11 generate.py
      - name: GIT Commit Artifacts
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
